# Generated by Django 5.0.2 on 2024-03-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_cargo_regional_remove_client_municipality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFicha', models.CharField(max_length=15, unique=True, verbose_name='Numero de Ficha')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Formacion')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='persona',
            new_name='Aprendiz',
        ),
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'ordering': ['id'], 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('tipoDocumento', models.CharField(choices=[('Cédula de ciudadanía', 'CC'), ('Cédula de extranjería', 'CE'), ('NIT', 'NI'), ('Tarjeta de identidad', 'TI'), ('Registro civil de nacimiento', 'RC'), ('Pasaporte', 'PSP'), ('Documento de identificación extranjero', 'DIE'), ('Salvoconducto de permanencia', 'SP')], default='C.C', max_length=50, verbose_name='TipoDocumento')),
                ('numeroDocumento', models.CharField(blank=True, max_length=10, null=True, verbose_name='numeroDocumento')),
                ('tipoSangre', models.CharField(choices=[('O negativo', 'O-'), ('O positivo', 'O+'), ('A negativo', 'A-'), ('A positivo', 'A+'), ('B negativo', 'B-'), ('B positivo', 'B+'), ('AB negativo', 'AB-'), ('AB positivo', 'AB+')], default='0-', max_length=50, verbose_name='TipoDocumento')),
                ('cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.cargo')),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionario',
                'ordering': ['id'],
            },
        ),
    ]
