# Generated by Django 5.0.2 on 2024-03-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_formacion_options_alter_aprendiz_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='Formacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.formacion'),
        ),
    ]
