# Generated by Django 4.1.13 on 2024-03-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_aprendiz_formacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoimg', models.ImageField(blank=True, null=True, upload_to='logo%Y%m%d')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
                'ordering': ['id'],
            },
        ),
    ]
