# Generated by Django 4.1.13 on 2024-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_logo_logoimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logoimg',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
