# Generated by Django 4.1.13 on 2024-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_logo_logoimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='imgAprendices',
            field=models.ImageField(blank=True, null=True, upload_to='Aprendices'),
        ),
    ]
