# Generated by Django 4.1.13 on 2024-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_aprendiz_imgaprendices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='tipoSangre',
            field=models.CharField(choices=[('O negativo', 'RH O-'), ('O positivo', 'RH O+'), ('A negativo', 'RH A-'), ('A positivo', 'RH A+'), ('B negativo', 'RH B-'), ('B positivo', 'RH B+'), ('AB negativo', 'RH AB-'), ('AB positivo', 'RH AB+')], default='0-', max_length=50, verbose_name='TipoSangre'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipoSangre',
            field=models.CharField(choices=[('O negativo', 'RH O-'), ('O positivo', 'RH O+'), ('A negativo', 'RH A-'), ('A positivo', 'RH A+'), ('B negativo', 'RH B-'), ('B positivo', 'RH B+'), ('AB negativo', 'RH AB-'), ('AB positivo', 'RH AB+')], default='0-', max_length=50, verbose_name='TipoDocumento'),
        ),
    ]
